name: Shell

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-shell-scripts:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run shfmt and shellcheck
        uses: luizm/action-sh-checker@v0.8.0
        env:
          SHFMT_OPTS: -d -s -w -i 4 -ln bash
